name: smarttechinnovate.admin.ui - production deploy

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'install Node.js 20.x'

- script: npm install -g pnpm
  displayName: 'install pnpm'

- script: pnpm install
  displayName: 'install project dependencies'

- script: pnpm build
  displayName: 'build Vite application'
  env:
    VITE_GATEWAY_API: https://smartconsig-gateway-live.victoriousocean-22a8a528.brazilsouth.azurecontainerapps.io/api/v1
    VITE_AUTH_API: https://feijuca-auth-api.victoriousocean-22a8a528.brazilsouth.azurecontainerapps.io/api/v1
    CI: true

- script: |
    npm install -g netlify-cli
    netlify deploy --site a7857b39-8740-4b09-b1ac-7f2a8927bc5e --auth $(NETLIFY_AUTH_TOKEN) --dir=dist --prod --message "deploy from azure pipeline $(Build.BuildNumber)"
  displayName: 'Deploy to Netlify Production'
  env:
    NETLIFY_SITE_ID: a7857b39-8740-4b09-b1ac-7f2a8927bc5e
    NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
