name: workflow — trigger comanda production deployment

on:
  push:
    branches: [master]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      comanda_boundaries_orchestrator: ${{ steps.filter.outputs.comanda_boundaries_orchestrator }}
      comanda_boundaries_orders: ${{ steps.filter.outputs.comanda_boundaries_orders }}
      comanda_boundaries_payments: ${{ steps.filter.outputs.comanda_boundaries_payments }}
      comanda_boundaries_profiles: ${{ steps.filter.outputs.comanda_boundaries_profiles }}
      comanda_boundaries_stores: ${{ steps.filter.outputs.comanda_boundaries_stores }}
      comanda_boundaries_subscriptions: ${{ steps.filter.outputs.comanda_boundaries_subscriptions }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: detect changed paths
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            comanda_boundaries_orchestrator:
              - 'Boundaries/Comanda.Orchestrator/**'
            comanda_boundaries_orders:
              - 'Boundaries/Comanda.Orders/**'
            comanda_boundaries_payments:
              - 'Boundaries/Comanda.Payments/**'
            comanda_boundaries_profiles:
              - 'Boundaries/Comanda.Profiles/**'
            comanda_boundaries_stores:
              - 'Boundaries/Comanda.Stores/**'
            comanda_boundaries_subscriptions:
              - 'Boundaries/Comanda.Subscriptions/**'

  deploy-comanda-orchestrator:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_orchestrator == 'true'
    uses: ./.github/workflows/template-deployment.yml
    with:
        service_path: Boundaries/Comanda.Orchestrator
        image_name: httpsrichardy/comanda.orchestrator
        deploy_url_secret: ORCHESTRATOR_PRODUCTION_DEPLOY_WEBHOOK_URL
    secrets: inherit

  deploy-comanda-orders:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_orders == 'true'
    uses: ./.github/workflows/template-deployment.yml
    with:
        service_path: Boundaries/Comanda.Orders
        image_name: httpsrichardy/comanda.orders
        deploy_url_secret: ORDERS_PRODUCTION_DEPLOY_WEBHOOK_URL
    secrets: inherit

  deploy-comanda-payments:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_payments == 'true'
    uses: ./.github/workflows/template-deployment.yml
    with:
        service_path: Boundaries/Comanda.Payments
        image_name: httpsrichardy/comanda.payments
        deploy_url_secret: PAYMENTS_PRODUCTION_DEPLOY_WEBHOOK_URL
    secrets: inherit

  deploy-comanda-profiles:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_profiles == 'true'
    uses: ./.github/workflows/template-deployment.yml
    with:
        service_path: Boundaries/Comanda.Profiles
        image_name: httpsrichardy/comanda.profiles
        deploy_url_secret: PROFILES_PRODUCTION_DEPLOY_WEBHOOK_URL
    secrets: inherit

  deploy-comanda-stores:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_stores == 'true'
    uses: ./.github/workflows/template-deployment.yml
    with:
        service_path: Boundaries/Comanda.Stores
        image_name: httpsrichardy/comanda.stores
        deploy_url_secret: STORES_PRODUCTION_DEPLOY_WEBHOOK_URL
    secrets: inherit

  deploy-comanda-subscriptions:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_subscriptions == 'true'
    uses: ./.github/workflows/template-deployment.yml
    with:
        service_path: Boundaries/Comanda.Subscriptions
        image_name: httpsrichardy/comanda.subscriptions
        deploy_url_secret: SUBSCRIPTIONS_PRODUCTION_DEPLOY_WEBHOOK_URL
    secrets: inherit
