name: pipeline ci/cd - publish comanda packages

on:
  push:
    branches:
      - master
    paths:
      - 'Artifacts/Comanda.Internal.Contracts/**'
      - 'Artifacts/Comanda.Internal.AspNet/**'

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      comanda_internal_contracts: ${{ steps.filter.outputs.comanda_internal_contracts }}
      comanda_internal_aspnet: ${{ steps.filter.outputs.comanda_internal_aspnet }}

    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: detect changed paths
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            comanda_internal_contracts:
              - 'Artifacts/Comanda.Internal.Contracts/**'
            comanda_internal_aspnet:
              - 'Artifacts/Comanda.Internal.AspNet/**'

  # publish this package if there are changes in the corresponding path
  publish-comanda-internal-contracts:
    needs: changes
    if: needs.changes.outputs.comanda_internal_contracts == 'true'
    uses: ./.github/workflows/template-publish-package.yml
    with:
      working_directory: Artifacts/Comanda.Internal.Contracts/Source
      dotnet_version: 9.0.x
    secrets: inherit

  # publish this package if there are changes in the corresponding path
  publish-comanda-internal-aspnet:
    needs: changes
    if: needs.changes.outputs.comanda_internal_aspnet == 'true'
    uses: ./.github/workflows/template-publish-package.yml
    with:
      working_directory: Artifacts/Comanda.Internal.AspNet/Source
      dotnet_version: 9.0.x
    secrets: inherit
