name: pipeline ci/cd — trigger pull request quality assurance

on:
  pull_request:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # filters for boundaries
      comanda_boundaries_orchestrator: ${{ steps.filter.outputs.comanda_boundaries_orchestrator }}
      comanda_boundaries_orders: ${{ steps.filter.outputs.comanda_boundaries_orders }}
      comanda_boundaries_payments: ${{ steps.filter.outputs.comanda_boundaries_payments }}
      comanda_boundaries_profiles: ${{ steps.filter.outputs.comanda_boundaries_profiles }}
      comanda_boundaries_stores: ${{ steps.filter.outputs.comanda_boundaries_stores }}
      comanda_boundaries_subscriptions: ${{ steps.filter.outputs.comanda_boundaries_subscriptions }}

      # filters for packages
      comanda_internal_contracts: ${{ steps.filter.outputs.comanda_internal_contracts }}
      comanda_internal_aspnet: ${{ steps.filter.outputs.comanda_internal_aspnet }}

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: detect changed paths
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            comanda_boundaries_orchestrator:
              - 'Boundaries/Comanda.Orchestrator/**'
            comanda_boundaries_orders:
              - 'Boundaries/Comanda.Orders/**'
            comanda_boundaries_payments:
              - 'Boundaries/Comanda.Payments/**'
            comanda_boundaries_profiles:
              - 'Boundaries/Comanda.Profiles/**'
            comanda_boundaries_stores:
              - 'Boundaries/Comanda.Stores/**'
            comanda_boundaries_subscriptions:
              - 'Boundaries/Comanda.Subscriptions/**'
            comanda_internal_contracts:
              - 'Artifacts/Comanda.Internal.Contracts/**'
            comanda_internal_aspnet:
              - 'Artifacts/Comanda.Internal.AspNet/**'

# run build and tests for comanda orchestrator if there are changes in the corresponding path
  quality-assurance-boundaries-orchestrator:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_orchestrator == 'true'
    uses: ./.github/workflows/template-quality-assurance.yml
    with:
        service_path: Boundaries/Comanda.Orchestrator

# run build and tests for comanda orders if there are changes in the corresponding path
  quality-assurance-boundaries-orders:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_orders == 'true'
    uses: ./.github/workflows/template-quality-assurance.yml
    with:
        service_path: Boundaries/Comanda.Orders

# run build and tests for comanda payments if there are changes in the corresponding path
  quality-assurance-boundaries-payments:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_payments == 'true'
    uses: ./.github/workflows/template-quality-assurance.yml
    with:
        service_path: Boundaries/Comanda.Payments

# run build and tests for comanda profiles if there are changes in the corresponding path
  quality-assurance-boundaries-profiles:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_profiles == 'true'
    uses: ./.github/workflows/template-quality-assurance.yml
    with:
        service_path: Boundaries/Comanda.Profiles

# run build and tests for comanda stores if there are changes in the corresponding path
  quality-assurance-boundaries-stores:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_stores == 'true'
    uses: ./.github/workflows/template-quality-assurance.yml
    with:
        service_path: Boundaries/Comanda.Stores

# run build and tests for comanda subscriptions if there are changes in the corresponding path
  quality-assurance-boundaries-subscriptions:
    needs: changes
    if: needs.changes.outputs.comanda_boundaries_subscriptions == 'true'
    uses: ./.github/workflows/template-quality-assurance.yml
    with:
        service_path: Boundaries/Comanda.Subscriptions

# run build and tests for comanda internal contracts if there are changes in the corresponding path
  quality-assurance-internal-contracts:
    needs: changes
    if: needs.changes.outputs.comanda_internal_contracts == 'true'
    uses: ./.github/workflows/template-quality-assurance.yml
    with:
        service_path: Artifacts/Comanda.Internal.Contracts

# run build and tests for comanda internal aspnet if there are changes in the corresponding path
  quality-assurance-internal-aspnet:
    needs: changes
    if: needs.changes.outputs.comanda_internal_aspnet == 'true'
    uses: ./.github/workflows/template-quality-assurance.yml
    with:
        service_path: Artifacts/Comanda.Internal.AspNet
